# Generated by Django 4.0 on 2022-01-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suryamitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Full Name')),
                ('registeration_id', models.CharField(max_length=150, unique=True)),
                ('certificate_copy', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Mobile Number')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'verbose_name': 'Suryamitra',
                'verbose_name_plural': 'Suryamitra',
                'db_table': 'suryamitra',
            },
        ),
    ]
