# Generated by Django 4.0 on 2022-01-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_suryamitra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suryamitra',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='suryamitra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='suryamitra',
            name='role',
        ),
        migrations.AddField(
            model_name='suryamitra',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
