# Generated by Django 4.0 on 2022-01-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_suryamitra_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuryamitraProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Full Name')),
                ('registeration_id', models.CharField(max_length=150, unique=True)),
                ('certificate_copy', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Suryamitra',
                'verbose_name_plural': 'Suryamitra',
                'db_table': 'suryamitra_profile',
            },
        ),
        migrations.DeleteModel(
            name='Suryamitra',
        ),
    ]
