# Generated by Django 4.0 on 2022-01-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_suryamitraprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suryamitraprofile',
            options={'verbose_name': 'Suryamitra_profile', 'verbose_name_plural': 'Suryamitra_profile'},
        ),
        migrations.RemoveField(
            model_name='suryamitraprofile',
            name='name',
        ),
    ]
