# Generated by Django 4.0 on 2022-01-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_suryamitraprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suryamitraprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
