# Generated by Django 4.0 on 2022-01-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_suryamitraprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suryamitraprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
