# Generated by Django 4.0 on 2022-01-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_suryamitraprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suryamitraprofile',
            options={'verbose_name': 'Suryamitra', 'verbose_name_plural': 'Suryamitra'},
        ),
        migrations.AddField(
            model_name='suryamitraprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='suryamitraprofile',
            name='name',
            field=models.CharField(default='Name', max_length=500, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='suryamitraprofile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterModelTable(
            name='suryamitraprofile',
            table='suryamitra',
        ),
    ]
