# Generated by Django 4.0 on 2022-01-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_suryamitraprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suryamitraprofile',
            name='user',
        ),
    ]
