# Generated by Django 4.0 on 2022-01-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_suryamitraprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suryamitraprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='suryamitraprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='suryamitraprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
