# Generated by Django 4.0 on 2022-01-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_suryamitraprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suryamitraprofile',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
