# Generated by Django 4.0 on 2022-01-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuryamitraProfile',
        ),
    ]
