# Generated by Django 4.0 on 2022-01-18 15:35

from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_delete_suryamitraprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuryamitraProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
            ],
            options={
                'verbose_name': 'Suryamitra',
                'verbose_name_plural': 'Suryamitra',
                'db_table': 'suryamitra',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
