# Generated by Django 4.0 on 2022-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_suryamitraprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='suryamitraprofile',
            name='registeration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
