# Generated by Django 4.0 on 2022-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_suryamitraprofile_registeration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suryamitraprofile',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='./users/images/suryamitra/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='./users/images/users/', verbose_name='Profile Photo'),
        ),
    ]
