# Generated by Django 4.0 on 2022-01-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Contact Number'),
        ),
    ]
