# Generated by Django 4.0 on 2022-01-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_suryamitraprofile_password_suryamitra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suryamitraprofile',
            name='password_suryamitra',
        ),
    ]
