# Generated by Django 4.0 on 2022-01-19 09:40

from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_suryamitraprofile_password_suryamitra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('discom_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ca_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customer',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
