# Generated by Django 4.0 on 2022-01-20 06:53

from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_line1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('street_line2', models.CharField(blank=True, max_length=100, verbose_name='Address 2')),
                ('zipcode', models.CharField(blank=True, max_length=9, verbose_name='ZIP code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Addressess',
                'verbose_name_plural': 'Address',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='DiscomProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Discom Code')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TechSupportProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('tech_support_log', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_country',
            field=models.CharField(blank=True, default='India', max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='PinCode'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='ca_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CA Number'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='registeration_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registeration ID'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='discom_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.discomprofile', verbose_name='Discom'),
        ),
    ]
