# Generated by Django 4.0 on 2022-01-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_address_discomprofile_techsupportprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='address_2',
            new_name='address_line_2',
        ),
    ]
