# Generated by Django 4.0 on 2022-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pvproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvproducts',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
