# Generated by Django 4.0 on 2022-01-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pvproducts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvproducts',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
