# Generated by Django 4.0 on 2022-01-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_pvmodels_models_rename_pvproducts_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
