# Generated by Django 4.0 on 2022-01-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_models_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['sku'], 'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['sku'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
