# Generated by Django 4.0 on 2022-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_models_options_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='./products/images/'),
        ),
    ]
