# Generated by Django 4.0 on 2022-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_models_grid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ['sku'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['sku'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AddField(
            model_name='models',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='./products/images/'),
        ),
    ]
