# Generated by Django 4.0 on 2022-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_models_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_quantity',
            field=models.IntegerField(default=0, verbose_name='Available Qty'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(verbose_name='Required Qty'),
        ),
    ]
