# Generated by Django 4.0 on 2022-01-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_available_quantity_alter_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sku_model',
        ),
        migrations.AddField(
            model_name='models',
            name='components',
            field=models.ManyToManyField(to='products.Products'),
        ),
    ]
