# Generated by Django 4.0 on 2022-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_products_sku_model_models_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='components',
            field=models.ManyToManyField(related_name='component_set', related_query_name='component', to='products.Products', verbose_name='Compnents'),
        ),
    ]
