# Generated by Django 4.0 on 2022-01-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_models_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='required_quanity',
            field=models.IntegerField(default=0, verbose_name='Rquired Qty'),
        ),
    ]
