# Generated by Django 4.0 on 2022-01-14 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_remove_suryamitraprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('products', models.JSONField()),
                ('created_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('order_status', models.CharField(default='Ordered', max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
    ]
