# Generated by Django 4.0 on 2022-01-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_ca_number_ordersmodel_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
