# Generated by Django 4.0 on 2022-01-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordersmodel_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='suryamitra',
        ),
    ]
